### ISSUE TITLE
Question :  Interpretation of prob_token_topic

### ISSUE THREAD

**Issue by AllardJM** [columbia-applied-data-science/rosetta#43]
Hey guys,

I was curious about how to interpret output from the prob_token_topic function. I noticed that the probability outcome changes depending on the number of topics being conditioned on.

The probability of 'kennedy' in topic 0 will be different under the following:
lda.prob_token_topic(token='kennedy', c_topic=['topic_0'])
lda.prob_token_topic(token='kennedy', c_topic=['topic_0', 'topic_3'])

Is this as expected? How should these outcomes be interpreted?

**Comment by langmore** [comment]
They are expected to change.  In the first its the probability of seeing
the word Kennedy given you are drawing from topic_0, and in the second
topic_0 and topic_3.

**Comment by AllardJM** [comment]
I did not realize that drawing from topic_0 and topic_3 changed the 
probability of drawing from topic_0. I thought the distribution over 
words within a topic were fixed.  Thanks, need to read more about LDA.



On 1/28/2015 11:24 PM, Ian Langmore wrote:
They are expected to change. In the first its the probability of seeing
> the word Kennedy given you are drawing from topic_0, and in the second
> topic_0 and topic_3.

**Comment by langmore** [comment]
Just read about conditional probability.   Conditioning on different things changes the distribution.  In this case you're conditioning on "topic in"

**Comment by AllardJM** [comment]
Thanks. Yeah I get the simple case that p(X=x | Y=y) != p(X=x | Y=y1 and 
Z=z1) where each value is a scalar. Trying to consider what it means to 
have this output a value separately for y1 and z1.

Is the way to think about it that lda.prob_token_topic(token='kennedy', 
c_topic=['topic_0', 'topic_3']) is over the intersection of documents 
that are made up of topic_0 and topic_3 and because of this, 
p(token=kennedy | topic_0) when considering the subset of topic_0 that 
is overlapping with topic_3 is different than p(token=kennedy | topic_0) 
when considering all documents from topic 0 (ignoring topic_3 membership)?

**Comment by AllardJM** [comment]
One more quick question if you don't mind (not sure if there is a more suitable place for questions?), am I correct that the following attributes of an object of class LDAResults relate to the following converged elements of LDA  (say from page 3 of http://cran.r-project.org/web/packages/topicmodels/vignettes/topicmodels.pdf):

*The rows of <b>pr_doc_topic</b> are <i>vectors of theta</i>, probability of topic k occurring in document d for any given word (shows the relative mixture of topics in each document); p(topic|document).

*The columns of <b>pr_token_topic</b> are vectors of beta, the distribution of words in topic t; p(word | topic).

Both of these need to be normalized in order to be a probability though (<b>pr_doc_topic row-wise</b> and <b>pr_token_topic column-wise</b>).

**Comment by AllardJM** [comment]
I dug deeper into the code and see now that the joint distribution of [topics and tokens] and [topics and docs] are created from the raw VW output to then allow querying of the joint for conditions. So that for example, to see the vectors of Beta, as referenced above, are found by lda.prob_token_topic(c_topic=['topic_0']) - giving for example topic_0.
